# Tutorial 1: Basics of CrypTen Tensors

We now have a high-level understanding of how secure MPC works. Through these tutorials, we will explain how to use CrypTen to carry out secure operations on encrypted tensors. In this tutorial, we will introduce a fundamental building block in CrypTen, called a ```CrypTensor```.  ```CrypTensors``` are encrypted ```torch``` tensors that can be used for computing securely on data. 

CrypTen currently only supports secure MPC protocols (though we intend to add support for other advanced encryption protocols). Using the ```mpc``` backend, ```CrypTensors``` act as ```torch``` tensors whose values are encrypted using secure MPC protocols. Tensors created using the ```mpc``` backend are called ```MPCTensors```. We will go into greater detail about ```MPCTensors``` in Tutorial 2. 

Let's begin by importing ```crypten``` and ```torch``` libraries. (If the imports fail, please see the installation instructions in the README.)

In [2]:
import crypten
import torch
from crypten.config import cfg

crypten.init()

In [8]:
import crypten
import torch
# import logging
import timeit
from crypten.config import cfg

# logging.basicConfig(filename='mylogs.log', level=logging.DEBUG)

crypten.init()

torch.set_printoptions(sci_mode=False)

#Construct example input CrypTensor
x = torch.arange(0, 5, 0.01)
x_enc = crypten.cryptensor(x)
num_iters = 1
print_terms = 10


print("Exponential:")
print("  Exact :", x.exp()[:print_terms])
with cfg.temp_override({"functions.exp_method": 'limit'}):
    start1 = timeit.default_timer()
    for _ in range(num_iters):
        z_enc = x_enc.exp()  # Private
    print("  Approx:", num_iters, "iterations in",  timeit.default_timer() - start1, "sec.:", z_enc.get_plain_text()[:print_terms])
with cfg.temp_override({"functions.exp_method": 'lut'}):
    with cfg.temp_override({"functions.exp_all_neg": False}):
        start1 = timeit.default_timer()
        for _ in range(num_iters):
            z_enc = x_enc.exp()  # Private
        print("  LUT   :", num_iters, "iterations in",  timeit.default_timer() - start1, "sec.:", z_enc.get_plain_text()[:print_terms])


print("\nLogarithm (LUT faster):")
print("  Exact :", x.log()[:print_terms])
with cfg.temp_override({"functions.log_method": 'iter'}):
    start1 = timeit.default_timer()
    for _ in range(num_iters):
        z_enc = x_enc.log()  # Private
    print("  Approx:", num_iters, "iterations in",  timeit.default_timer() - start1, "sec.:", z_enc.get_plain_text()[:print_terms])
with cfg.temp_override({"functions.log_method": 'lut'}):
    start1 = timeit.default_timer()
    for _ in range(num_iters):
        z_enc = x_enc.log()  # Private
    print("  LUT   :", num_iters, "iterations in",  timeit.default_timer() - start1, "sec.:", z_enc.get_plain_text()[:print_terms])


print("\nReciprocal:")
print("  Exact :", x.reciprocal()[:print_terms])
with cfg.temp_override({"functions.reciprocal_method": 'NR'}):
    with cfg.temp_override({"functions.exp_method": 'limit'}):
        start1 = timeit.default_timer()
        for _ in range(num_iters):
            z_enc = x_enc.reciprocal()  # Private
        print("  Approx:", num_iters, "iterations in",  timeit.default_timer() - start1, "sec.:", z_enc.get_plain_text()[:print_terms])
with cfg.temp_override({"functions.reciprocal_method": 'lut'}):
    start1 = timeit.default_timer()
    for _ in range(num_iters):
        z_enc = x_enc.reciprocal()  # Private
    print("  LUT   :", num_iters, "iterations in",  timeit.default_timer() - start1, "sec.:", z_enc.get_plain_text()[:print_terms])


print("\nSquare Root: (LUT faster)")
print("  Exact :", x.sqrt()[:print_terms])
with cfg.temp_override({"functions.sqrt_method": 'NR'}):
    with cfg.temp_override({"functions.inv_sqrt_method": 'NR'}):
        start1 = timeit.default_timer()
        for _ in range(num_iters):
            z_enc = x_enc.sqrt()  # Private
        print("  Approx:", num_iters, "iterations in",  timeit.default_timer() - start1, "sec.:", z_enc.get_plain_text()[:print_terms])
with cfg.temp_override({"functions.sqrt_method": 'lut'}):
    with cfg.temp_override({"functions.inv_sqrt_method": 'lut'}):
        start1 = timeit.default_timer()
        for _ in range(num_iters):
            z_enc = x_enc.sqrt()  # Private
        print("  LUT   :", num_iters, "iterations in",  timeit.default_timer() - start1, "sec.:", z_enc.get_plain_text()[:print_terms])


print("\nSin:")
print("  Exact :", x.sin()[:print_terms])
with cfg.temp_override({"functions.trigonometry_method": 'NR'}):
    start1 = timeit.default_timer()
    for _ in range(num_iters):
        z_enc = x_enc.sin()  # Private
    print("  Approx:", num_iters, "iterations in",  timeit.default_timer() - start1, "sec.:", z_enc.get_plain_text()[:print_terms])
with cfg.temp_override({"functions.trigonometry_method": 'lut'}):
    start1 = timeit.default_timer()
    for _ in range(num_iters):
        z_enc = x_enc.sin()  # Private
    print("  LUT   :", num_iters, "iterations in",  timeit.default_timer() - start1, "sec.:", z_enc.get_plain_text()[:print_terms])


print("\nCos:")
print("  Exact :", x.cos()[:print_terms])
with cfg.temp_override({"functions.trigonometry_method": 'NR'}):
    start1 = timeit.default_timer()
    for _ in range(num_iters):
        z_enc = x_enc.cos()  # Private
    print("  Approx:", num_iters, "iterations in",  timeit.default_timer() - start1, "sec.:", z_enc.get_plain_text()[:print_terms])
with cfg.temp_override({"functions.trigonometry_method": 'lut'}):
    start1 = timeit.default_timer()
    for _ in range(num_iters):
        z_enc = x_enc.cos()  # Private
    print("  LUT   :", num_iters, "iterations in",  timeit.default_timer() - start1, "sec.:", z_enc.get_plain_text()[:print_terms])


print("\nSigmoid:")
print("  Exact :", x.sigmoid()[:print_terms])
with cfg.temp_override({"functions.sigmoid_tanh_method": 'reciprocal'}):
    with cfg.temp_override({"functions.reciprocal_method": 'NR'}):
        with cfg.temp_override({"functions.exp_method": 'limit'}):
            start1 = timeit.default_timer()
            for _ in range(num_iters):
                z_enc = x_enc.sigmoid()  # Private
            print("  Approx:", num_iters, "iterations in",  timeit.default_timer() - start1, "sec.:", z_enc.get_plain_text()[:print_terms])
with cfg.temp_override({"functions.sigmoid_tanh_method": 'lut'}):
    start1 = timeit.default_timer()
    for _ in range(num_iters):
        z_enc = x_enc.sigmoid()  # Private
    print("  LUT   :", num_iters, "iterations in",  timeit.default_timer() - start1, "sec.:", z_enc.get_plain_text()[:print_terms])



Exponential:
  Exact : tensor([1.0000, 1.0101, 1.0202, 1.0305, 1.0408, 1.0513, 1.0618, 1.0725, 1.0833,
        1.0942])
  Approx: 1 iterations in 0.0037608330021612346 sec.: tensor([1.0000, 1.0078, 1.0197, 1.0276, 1.0397, 1.0478, 1.0601, 1.0685, 1.0809,
        1.0937])
  LUT   : 1 iterations in 0.2518613339634612 sec.: tensor([1.0005, 1.0103, 1.0202, 1.0302, 1.0403, 1.0516, 1.0619, 1.0723, 1.0828,
        1.0945])

Logarithm (LUT faster):
  Exact : tensor([   -inf, -4.6052, -3.9120, -3.5066, -3.2189, -2.9957, -2.8134, -2.6593,
        -2.5257, -2.4079])
  Approx: 1 iterations in 0.08226504101185128 sec.: tensor([-9.3201, -9.1931, -9.0670, -8.9430, -8.7983, -8.6792, -8.5625, -8.4260,
        -8.3142, -8.2043])
  LUT   : 1 iterations in 0.1871779999928549 sec.: tensor([-7.8846, -4.5797, -3.9108, -3.5135, -3.2300, -2.9897, -2.8123, -2.6617,
        -2.5308, -2.4042])

Reciprocal:
  Exact : tensor([     inf, 100.0000,  50.0000,  33.3333,  25.0000,  20.0000,  16.6667,
         14.2857,  12

### Creating Encrypted Tensors
CrypTen provides a ```crypten.cryptensor``` factory function, similar to ```torch.tensor```, to make creating ```CrypTensors``` easy. 

Let's begin by creating a ```torch``` tensor and encrypting it using ```crypten.cryptensor```. To decrypt a ```CrypTensor```, use ```get_plain_text()``` to return the original tensor.  (```CrypTensors``` can also be created directly from a list or an array.)


In [2]:
# Create torch tensor
x = torch.tensor([1.0, 2.0, 3.0])

# Encrypt x
x_enc = crypten.cryptensor(x)

# Decrypt x
x_dec = x_enc.get_plain_text()
crypten.print(x_dec)


# Create python list
y = [4.0, 5.0, 6.0]

# Encrypt x
y_enc = crypten.cryptensor(y)

# Decrypt x
y_dec = y_enc.get_plain_text()
crypten.print(y_dec)

tensor([1., 2., 3.])
tensor([4., 5., 6.])


## Operations on Encrypted Tensors
Now let's look at what we can do with our ```CrypTensors```.

#### Arithmetic Operations
We can carry out regular arithmetic operations between ```CrypTensors```, as well as between ```CrypTensors``` and plaintext tensors. Note that these operations never reveal any information about encrypted tensors (internally or externally) and return an encrypted tensor output.

In [3]:
#Arithmetic operations between CrypTensors and plaintext tensors
x_enc = crypten.cryptensor([1.0, 2.0, 3.0])

y = 2.0
y_enc = crypten.cryptensor(2.0)


# Addition
z_enc1 = x_enc + y      # Public
z_enc2 = x_enc + y_enc  # Private
crypten.print("\nPublic  addition:", z_enc1.get_plain_text())
crypten.print("Private addition:", z_enc2.get_plain_text())


# Subtraction
z_enc1 = x_enc - y      # Public
z_enc2 = x_enc - y_enc  # Private
crypten.print("\nPublic  subtraction:", z_enc1.get_plain_text())
print("Private subtraction:", z_enc2.get_plain_text())

# Multiplication
z_enc1 = x_enc * y      # Public
z_enc2 = x_enc * y_enc  # Private
print("\nPublic  multiplication:", z_enc1.get_plain_text())
print("Private multiplication:", z_enc2.get_plain_text())

# Division
z_enc1 = x_enc / y      # Public
z_enc2 = x_enc / y_enc  # Private
print("\nPublic  division:", z_enc1.get_plain_text())
print("Private division:", z_enc2.get_plain_text())


Public  addition: tensor([3., 4., 5.])
Private addition: tensor([3., 4., 5.])

Public  subtraction: tensor([-1.,  0.,  1.])
Private subtraction: tensor([-1.,  0.,  1.])

Public  multiplication: tensor([2., 4., 6.])
Private multiplication: tensor([2., 4., 6.])

Public  division: tensor([0.5000, 1.0000, 1.5000])
Private division: tensor([0.5000, 1.0000, 1.5000])


#### Comparisons
Similarly, we can compute element-wise comparisons on ```CrypTensors```. Like arithmetic operations, comparisons performed on ```CrypTensor```s will return a ```CrypTensor``` result. Decrypting these result ```CrypTensor```s will evaluate to 0's and 1's corresponding to ```False``` and ```True``` values respectively.

In [4]:
#Construct two example CrypTensors
x_enc = crypten.cryptensor([1.0, 2.0, 3.0, 4.0, 5.0])

y = torch.tensor([5.0, 4.0, 3.0, 2.0, 1.0])
y_enc = crypten.cryptensor(y)

# Print values:
print("x: ", x_enc.get_plain_text())
print("y: ", y_enc.get_plain_text())

# Less than
z_enc1 = x_enc < y      # Public
z_enc2 = x_enc < y_enc  # Private
print("\nPublic  (x < y) :", z_enc1.get_plain_text())
print("Private (x < y) :", z_enc2.get_plain_text())

# Less than or equal
z_enc1 = x_enc <= y      # Public
z_enc2 = x_enc <= y_enc  # Private
print("\nPublic  (x <= y):", z_enc1.get_plain_text())
print("Private (x <= y):", z_enc2.get_plain_text())

# Greater than
z_enc1 = x_enc > y      # Public
z_enc2 = x_enc > y_enc  # Private
print("\nPublic  (x > y) :", z_enc1.get_plain_text())
print("Private (x > y) :", z_enc2.get_plain_text())

# Greater than or equal
z_enc1 = x_enc >= y      # Public
z_enc2 = x_enc >= y_enc  # Private
print("\nPublic  (x >= y):", z_enc1.get_plain_text())
print("Private (x >= y):", z_enc2.get_plain_text())

# Equal
z_enc1 = x_enc == y      # Public
z_enc2 = x_enc == y_enc  # Private
print("\nPublic  (x == y):", z_enc1.get_plain_text())
print("Private (x == y):", z_enc2.get_plain_text())

# Not Equal
z_enc1 = x_enc != y      # Public
z_enc2 = x_enc != y_enc  # Private
print("\nPublic  (x != y):", z_enc1.get_plain_text())
print("Private (x != y):", z_enc2.get_plain_text())


x:  tensor([1., 2., 3., 4., 5.])
y:  tensor([5., 4., 3., 2., 1.])

Public  (x < y) : tensor([1., 1., 0., 0., 0.])
Private (x < y) : tensor([1., 1., 0., 0., 0.])

Public  (x <= y): tensor([1., 1., 1., 0., 0.])
Private (x <= y): tensor([1., 1., 1., 0., 0.])

Public  (x > y) : tensor([0., 0., 0., 1., 1.])
Private (x > y) : tensor([0., 0., 0., 1., 1.])

Public  (x >= y): tensor([0., 0., 1., 1., 1.])
Private (x >= y): tensor([0., 0., 1., 1., 1.])

Public  (x == y): tensor([0., 0., 1., 0., 0.])
Private (x == y): tensor([0., 0., 1., 0., 0.])

Public  (x != y): tensor([1., 1., 0., 1., 1.])
Private (x != y): tensor([1., 1., 0., 1., 1.])


#### Advanced mathematics
We are also able to compute more advanced mathematical functions on ```CrypTensors``` using iterative approximations. CrypTen provides MPC support for functions like reciprocal, exponential, logarithm, square root, tanh, etc. Notice that these are subject to numerical error due to the approximations used. 

Additionally, note that some of these functions will fail silently when input values are outside of the range of convergence for the approximations used. These do not produce errors because value are encrypted and cannot be checked without decryption. Exercise caution when using these functions. (It is good practice here to normalize input values for certain models.)

In [3]:
torch.set_printoptions(sci_mode=False)

#Construct example input CrypTensor
x = torch.tensor([0.1, 0.3, 0.5, 1.0, 1.5, 2.0, 2.5])
x_enc = crypten.cryptensor(x)

# Reciprocal
z = x.reciprocal()          # Public
z_enc = x_enc.reciprocal()  # Private
print("\nPublic  reciprocal:", z)
print("Private reciprocal:", z_enc.get_plain_text()[:print_terms])

# Logarithm
z = x.log()          # Public
z_enc = x_enc.log()  # Private
print("\nPublic  logarithm:", z)
print("Private logarithm:", z_enc.get_plain_text()[:print_terms])

# Exp
z = x.exp()          # Public
z_enc = x_enc.exp()  # Private
print("\nPublic  exponential:", z)
print("Private exponential:", z_enc.get_plain_text()[:print_terms])

# Sqrt
z = x.sqrt()          # Public
z_enc = x_enc.sqrt()  # Private
print("\nPublic  square root:", z)
print("Private square root:", z_enc.get_plain_text()[:print_terms])

# Tanh
z = x.tanh()          # Public
z_enc = x_enc.tanh()  # Private
print("\nPublic  tanh:", z)
print("Private tanh:", z_enc.get_plain_text()[:print_terms])


TypeError: Cannot mul <class 'crypten.mpc.mpc.MPCTensor'> with <class 'crypten.mpc.primitives.arithmetic.ArithmeticSharedTensor'>

## Control Flow using Encrypted Tensors

Note that ```CrypTensors``` cannot be used directly in conditional expressions. Because the tensor is encrypted, the boolean expression cannot be evaluated unless the tensor is decrypted first. Attempting to execute control flow using an encrypted condition will result in an error.

Some control flow can still be executed without decrypting, but must be executed using mathematical expressions. We have provided the function ```crypten.where(condition, x, y)``` to abstract this kind of conditional value setting.

The following example illustrates how to write this kind conditional logic for ```CrypTensors```.

In [6]:
x_enc = crypten.cryptensor(2.0)
y_enc = crypten.cryptensor(4.0)

a, b = 2, 3

# Normal Control-flow code will raise an error
try:
    if x_enc < y_enc:
        z = a
    else:
        z = b
except RuntimeError as error:
    print(f"RuntimeError caught: \"{error}\"\n")


# Instead use a mathematical expression
use_a = (x_enc < y_enc)
z_enc = use_a * a + (1 - use_a) * b
print("z:", z_enc.get_plain_text()[:print_terms])


# Or use the `where` function
z_enc = crypten.where(x_enc < y_enc, a, b)
print("z:", z_enc.get_plain_text()[:print_terms])

RuntimeError caught: "Cannot evaluate MPCTensors to boolean values"

z: tensor(2.)
z: tensor(2.)


### Advanced Indexing
CrypTen supports many of the operations that work on ```torch``` tensors. Encrypted tensors can be indexed, concatenated, stacked, reshaped, etc. For a full list of operations, see the CrypTen documentation.

In [7]:
x_enc = crypten.cryptensor([1.0, 2.0, 3.0])
y_enc = crypten.cryptensor([4.0, 5.0, 6.0])

# Indexing
z_enc = x_enc[:-1]
print("Indexing:\n", z_enc.get_plain_text()[:print_terms])

# Concatenation
z_enc = crypten.cat([x_enc, y_enc])
print("\nConcatenation:\n", z_enc.get_plain_text()[:print_terms])

# Stacking
z_enc = crypten.stack([x_enc, y_enc])
print('\nStacking:\n', z_enc.get_plain_text()[:print_terms])

# Reshaping
w_enc = z_enc.reshape(-1, 6)
print('\nReshaping:\n', w_enc.get_plain_text())

Indexing:
 tensor([1., 2.])

Concatenation:
 tensor([1., 2., 3., 4., 5., 6.])

Stacking:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])

Reshaping:
 tensor([[1., 2., 3., 4., 5., 6.]])



### Implementation Note

Due to internal implementation details, ```CrypTensors``` must be the first operand of operations that combine ```CrypTensors``` and ```torch``` tensors. That is, for a ```CrypTensor``` ```x_enc``` and a plaintext tensor ```y```:
- The expression ```x_enc < y``` is valid, but the equivalent expression ```y > x_enc``` will result in an error.
- The expression ```x_enc + y``` is valid, but the equivalent expression ```y + x_enc``` will result in an error.

We intend to add support for both expressions in the future.